#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)
TOOLS=${TOOLS-$(readlink -f "$SCRIPT_DIR/../tools")}

. <("$TOOLS/build-info" -e)

ARTIFACTS=${ARTIFACTS-$1}

TMP=$(mktemp -d)
trap 'rm -rf $TMP' EXIT
ASSETS=$TMP/assets
mkdir -p "$ASSETS"

unzip "$ARTIFACTS/PKGBUILD.$BUILD_GIT_REF.zip" -d "$ASSETS"

unzip "$ARTIFACTS/source-package.$BUILD_GIT_REF.ubuntu2204.zip" -d "$TMP"
for f in "$TMP/"*"$BUILD_VERSION.tar"; do
    UBUNTU_FILENAME=$(sed 's/.tar$/_ubuntu.tar/' <<< "$(basename "$f")")
    mv "$f" "$ASSETS/$UBUNTU_FILENAME"
done

gh release create --target=$BUILD_GIT_REF \
    "v$BUILD_VERSION" \
    "$ASSETS/PKGBUILD#Arch Linux PKGBUILD" \
    "$ASSETS/$UBUNTU_FILENAME#Ubuntu source package"
