#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)
TOOLS=${TOOLS-$(readlink -f "$SCRIPT_DIR/../tools")}

. <("$TOOLS/build-info" -e)

TAG="v$BUILD_VERSION"

if [ -n "${DRY_RUN-}" ]; then
    if gh release view "$TAG" &>/dev/null; then
        echo 1>&2 "release already exists: $TAG"
        exit 2
    else
        exit 0
    fi
fi

ARTIFACTS=${ARTIFACTS-$1}

TMP=$(mktemp -d)
trap 'rm -rf $TMP' EXIT
ASSETS=$TMP/assets
mkdir -p "$ASSETS"

unzip "$ARTIFACTS/PKGBUILD.$BUILD_GIT_REF.ubuntu-24.04.zip" -d "$ASSETS"

unzip "$ARTIFACTS/ubuntu-source-package.$BUILD_GIT_REF.ubuntu-24.04.ubuntu2404.zip" -d "$TMP"
for f in "$TMP/"*"$BUILD_VERSION.tar"; do
    UBUNTU_FILENAME=$(sed 's/.tar$/_ubuntu.tar/' <<< "$(basename "$f")")
    mv "$f" "$ASSETS/$UBUNTU_FILENAME"
done

gh release create --target="$BUILD_GIT_REF" \
    "$TAG" \
    "$ASSETS/PKGBUILD#Arch Linux PKGBUILD" \
    "$ASSETS/$UBUNTU_FILENAME#Ubuntu source package"
