#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)
. "$SCRIPT_DIR/../fetch.sh"

WD=$(mktemp -d)
trap 'rm -rf $WD' EXIT
TARBALL="$WD/linux.tar.gz"

VER=5.15.72
fetch -s \
    "https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-$VER.tar.gz" \
    "dada7fcc6fa0810300ec6d8e1f75bd4c8c935ca06ed39d74307f2a85674c1140" \
    "$TARBALL"

ROOT=$WD/root
mkdir -p "$ROOT"
tar -xvf "$TARBALL" -C "$ROOT" --strip-components=1 \
    "linux-$VER/tools/build" \
    "linux-$VER/tools/bpf" \
    "linux-$VER/tools/scripts"

TOOLS=("bpf_asm" "bpf_dbg")

make -C "$ROOT/tools/bpf" "${TOOLS[@]}"

PREFIX=${1-$PWD}
mkdir -p "$PREFIX"
for t in "${TOOLS[@]}"; do
    cp -v "$ROOT/tools/bpf/$t" "$PREFIX"
done
