#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)
BUILD=${BUILD-$SCRIPT_DIR/../build}
OUTPUT=${1-/dev/stdout}

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT

cat <<EOF > "$TMP"
| | runtime | build | check |
|-|---------|-------|-------|
EOF

arch() {
    export ARCH=$2
    DEPS=$BUILD/$ARCH/deps
    cat <<EOF
|$1| \`$("$DEPS" -r)\` | \`$("$DEPS" -b)\` | \`$("$DEPS" -c)\` |
EOF
}

arch "Ubuntu 22.04" ubuntu >> "$TMP"
arch "Arch Linux" archlinux >> "$TMP"

cp "$TMP" "$OUTPUT"
