#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)
BUILD=${BUILD-$SCRIPT_DIR/../build}
OUTPUT=${1-/dev/stdout}

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT

cat <<EOF > "$TMP"
| | runtime | build | check |
|-|---------|-------|-------|
EOF

os() {
    DEPS="$BUILD/$2/deps"
    RELEASE=${3-}

    deps() {
        env RELEASE="$RELEASE" "$DEPS" "$@"
    }

    cat <<EOF
|$1| $(deps -rm) | $(deps -bm) | $(deps -cm) |
EOF
}

os "Ubuntu 24.04" ubuntu noble >> "$TMP"
os "Ubuntu 22.04" ubuntu jammy >> "$TMP"
os "Arch Linux" archlinux >> "$TMP"

cp "$TMP" "$OUTPUT"
