#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)
PP=${PP-$SCRIPT_DIR/pp}

OUTPUT=/dev/stdout
while getopts "o:-" OPT; do
    case $OPT in
        o) OUTPUT=$OPTARG ;;
        -) break ;;
        ?) exit 2 ;;
    esac
done
shift $((OPTIND-1))

BPF_ASM=${BPF_ASM-bpf_asm}
if ! command -v "$BPF_ASM" > /dev/null; then
    BPF_ASM=$SCRIPT_DIR/bpf_asm
fi

"$PP" "$1" | "$BPF_ASM" -c > "$OUTPUT"
