#!/bin/bash

set -o nounset -o pipefail -o errexit

FD=${FD-rsfd}
INPUT=${1--}
OUTPUT=${2-/dev/stdout}

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT

cat "$INPUT" | while read F; do
    if [ -f "$F" ]; then
        if [ -x "$F" ]; then
            cat <<EOF >> "$TMP"
landlock_allow($FD, "$F", LANDLOCK_ACCESS_FS_READ_FILE|LANDLOCK_ACCESS_FS_EXECUTE);
EOF
        else
            cat <<EOF >> "$TMP"
landlock_allow($FD, "$F", LANDLOCK_ACCESS_FS_READ_FILE);
EOF
        fi
    elif [ -d "$F" ]; then
        cat <<EOF >> "$TMP"
landlock_allow($FD, "$F", LANDLOCK_ACCESS_FS_READ_FILE|LANDLOCK_ACCESS_FS_READ_DIR);
EOF
    else
        echo 1>&2 "unsupported filetype: $F"
        exit 1
    fi
done

cp "$TMP" "$OUTPUT"
