#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)
TOOLS=${TOOLS-$SCRIPT_DIR}

EXE=$1
OUTPUT=${2-/dev/stdout}

libs() {
    objdump -p "$1" | (grep NEEDED || true) | awk '{ print $2 }' \
        | xargs -I{} "$TOOLS/lib" {}
}

TMP=$(mktemp -d)
trap 'rm -rf $TMP' EXIT

I=0
libs "$EXE" | sort -u > "$TMP/$I"
while true; do
    mapfile -t L < "$TMP/$I"
    for l in "${L[@]}"; do
        echo "$l" >> "$TMP/$((I+1))"
        libs "$l" >> "$TMP/$((I+1))"
    done
    sort -u < "$TMP/$((I+1))" > "$TMP/$((I+2))"

    D=$(diff --brief "$TMP/$I" "$TMP/$((I+2))" || true)

    if [ -z "$D" ]; then
        cp "$TMP/$((I+2))" "$OUTPUT"
        exit 0
    fi

    I=$((I+2))
done
