#!/bin/bash

set -o nounset -o pipefail -o errexit

TOOLS=${TOOLS-$(readlink -f "$0" | xargs dirname)}
LIBS=()
OUTPUT=${OUTPUT-/dev/stdout}
VERSION=${VERSION-}
TCC=
while getopts "l:o:t-" OPT; do
    case $OPT in
        l) LIBS+=("-l$OPTARG") ;;
        o) OUTPUT=$OPTARG ;;
        v) VERSION=$VERSION ;;
        t) TCC=1 ;;
        -) break ;;
        ?) exit 2 ;;
    esac
done
shift $((OPTIND-1))

. <("$TOOLS/build-info" -e || cat /dev/null)

INPUT=$1

BASE_DIR=$(dirname "$INPUT")
if [ -z "$VERSION" ]; then
    if [ -n "${BUILD_GIT_REF-}" ]; then
        VERSION=$BUILD_GIT_REF
    else
        VERSION=unknown
    fi
fi

cp /dev/null "$OUTPUT"

if [ -n "$TCC" ]; then
    echo "#!/usr/bin/tcc -run ${LIBS[@]}" > "$OUTPUT"
fi

echo "// $(basename "$INPUT") ($VERSION) ($(date -Is))" >> "$OUTPUT"
echo >> "$OUTPUT"

if [ -n "$TCC" ] && [ -f "$OUTPUT" ]; then
    chmod +x "$OUTPUT"
fi

awk '{
if(/^#include\s+"[^"]*"/) {
    printf("// #include %s\n", $2)
    rc = system(sprintf("cat %s/%s", "'"$BASE_DIR"'", $2))
    if(rc != 0) exit(rc)
} else {
    print($0)
} }' "$INPUT" >> "$OUTPUT"
