name: Build and test
on: [ push ]

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    env:
      ARCH: ubuntu2204
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: build/deps

    - name: Cache tools
      id: cache-tools
      uses: actions/cache@v3
      env:
        cache-name: cache-tools
      with:
        path: |
          tools/bpf/bpf_*
          tools/lib
        key: ${{env.ARCH}}-${{env.cache-name}}-${{hashFiles('tools/lib.c')}}-${{hashFiles('tools/**/build')}}
    - if: ${{steps.cache-tools.outputs.cache-hit != 'true'}}
      name: Build tools
      run: make tools

    - name: Build
      run: make build LUA_PKG=lua54

    - name: Bundle distribution files
      run: build/dist -ddist

    - name: Archive distribution files
      uses: actions/upload-artifact@v3
      with:
        name: dist.${{github.sha}}.${{env.ARCH}}
        retention-days: 7
        path: dist

    - name: Test
      run: tools/test-harness -o.

    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: tests.${{github.sha}}.${{env.ARCH}}
        retention-days: 7
        path: "*-tests-*.tar.gz"

  archlinux:
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
    env:
      UNPRIVILEGED: arch
      TEST_OUTPUT_DIR: /tmp/tests
      ARCH: archlinux
    steps:
    - name: Install minimal dependencies
      run: pacman -Suy --noconfirm sudo fakeroot binutils which wget

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Create an unprivileged user
      run: |
        useradd -m $UNPRIVILEGED
        chown -R $UNPRIVILEGED:$UNPRIVILEGED .
        tee -a /etc/sudoers.d/$UNPRIVILEGED <<< "$UNPRIVILEGED ALL = NOPASSWD: $(which pacman)"

    - name: Create PKGBUILD
      run: ./mk
      working-directory: build/archlinux

    - name: Archive PKGBUILD
      uses: actions/upload-artifact@v3
      with:
        name: PKGBUILD.${{github.sha}}
        retention-days: 7
        path: "build/archlinux/PKGBUILD"

    - name: Build package
      run: sudo -u $UNPRIVILEGED makepkg -si --noconfirm
      working-directory: build/archlinux

    - name: Bundle distribution files
      run: build/dist -ddist

    - name: Archive distribution files
      uses: actions/upload-artifact@v3
      with:
        name: dist.${{github.sha}}.${{env.ARCH}}
        retention-days: 7
        path: dist

    - name: Test system installation
      run: |
        sudo -u $UNPRIVILEGED --preserve-env=TEST_OUTPUT_DIR env SUT=$(which hlua) tools/test-harness -c hlua
        sudo -u $UNPRIVILEGED --preserve-env=TEST_OUTPUT_DIR env SUT=$(which hpython) tools/test-harness -c hpython -o "$TEST_OUTPUT_DIR"

    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: tests.${{github.sha}}.${{env.ARCH}}
        retention-days: 7
        path: "${{env.TEST_OUTPUT_DIR}}/*-tests-*.tar.gz"
