name: Build and test
on: [ push ]

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    env:
      ARCH: ubuntu2204
      UNPRIVILEGED: ubuntu
      TEST_OUTPUT_DIR: /tmp/tests
    steps:
    - name: Install minimal dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends git sudo dpkg-dev gettext-base ca-certificates

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Create an unprivileged user
      run: |
        useradd -m $UNPRIVILEGED
        chown -R $UNPRIVILEGED:$UNPRIVILEGED .
        echo "$UNPRIVILEGED ALL = NOPASSWD: $(which apt-get)" | tee -a /etc/sudoers

    - name: Build package
      run: sudo -u $UNPRIVILEGED env SUDO=sudo build/ubuntu/mk

    - name: Install package
      run: dpkg -i build/ubuntu/out/*.deb

    - name: Test system installation
      run: |
        sudo -u $UNPRIVILEGED --preserve-env=TEST_OUTPUT_DIR env SUT=$(which hlua) tools/test-harness -c hlua
        sudo -u $UNPRIVILEGED --preserve-env=TEST_OUTPUT_DIR env SUT=$(which hpython) tools/test-harness -c hpython

    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: tests.${{github.sha}}.${{env.ARCH}}
        retention-days: 7
        path: "${{env.TEST_OUTPUT_DIR}}/*-tests-*.tar.gz"

  archlinux:
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
    env:
      ARCH: archlinux
      UNPRIVILEGED: arch
      TEST_OUTPUT_DIR: /tmp/tests
    steps:
    - name: Install minimal dependencies
      run: pacman -Suy --noconfirm sudo fakeroot binutils which wget git

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Create an unprivileged user
      run: |
        useradd -m $UNPRIVILEGED
        chown -R $UNPRIVILEGED:$UNPRIVILEGED .
        tee -a /etc/sudoers.d/$UNPRIVILEGED <<< "$UNPRIVILEGED ALL = NOPASSWD: $(which pacman)"

    - name: Create PKGBUILD
      run: ./mk
      working-directory: build/archlinux

    - name: Archive PKGBUILD
      uses: actions/upload-artifact@v3
      with:
        name: PKGBUILD.${{github.sha}}
        retention-days: 7
        path: "build/archlinux/PKGBUILD"

    - name: Build package
      run: sudo -u $UNPRIVILEGED makepkg -si --noconfirm
      working-directory: build/archlinux

    - name: Bundle distribution files
      run: build/dist -ddist

    - name: Archive distribution files
      uses: actions/upload-artifact@v3
      with:
        name: dist.${{github.sha}}.${{env.ARCH}}
        retention-days: 7
        path: dist

    - name: Test system installation
      run: |
        sudo -u $UNPRIVILEGED --preserve-env=TEST_OUTPUT_DIR env SUT=$(which hlua) tools/test-harness -c hlua
        sudo -u $UNPRIVILEGED --preserve-env=TEST_OUTPUT_DIR env SUT=$(which hpython) tools/test-harness -c hpython

    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: tests.${{github.sha}}.${{env.ARCH}}
        retention-days: 7
        path: "${{env.TEST_OUTPUT_DIR}}/*-tests-*.tar.gz"
