name: Continuous Dissemination
on: [ push ]

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Cache tools
      id: cache-tools
      uses: actions/cache@v3
      env:
        cache-name: cache-tools
      with:
        path: tools/bpf/bpf_*
        key: ${{runner.os}}-${{env.cache-name}}-${{hashFiles('tools/**/build')}}
    - if: ${{steps.cache-tools.outputs.cache-hit != 'true'}}
      name: Build tools
      run: make -C tools

    - name: Install dependencies
      run: sudo build/deps

    - name: Build
      run: make build LUA_PKG=lua54

    - name: Archive bundled stand-alone c-files
      uses: actions/upload-artifact@v3
      with:
        name: stand-alone-c-files.${{github.sha}}
        retention-days: 7
        path: |
          hlua/hlua.c
          hpython/hpython.c

    - name: Test
      run: tools/test-harness -vo.

    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: tests.${{github.sha}}
        retention-days: 7
        path: "*-tests-*.tar.gz"

  archlinux:
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
    steps:
    - name: Install minimal dependencies
      run: pacman -Suy --noconfirm sudo fakeroot binutils which wget

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Create an unprivileged user
      run: |
        useradd -m arch
        chown -R arch:arch .
        tee -a /etc/sudoers.d/arch <<< "arch ALL = NOPASSWD: $(which pacman)"

    - name: Create PKGBUILD
      run: ./mk
      working-directory: build/arch

    - name: Build package
      run: sudo -u arch env VERBOSE=1 makepkg -si --noconfirm
      working-directory: build/arch

    - name: Test system installation
      run: |
        make -C hlua test EXE=$(which hlua) VERBOSE=2
        make -C hpython test EXE=$(which hpython) VERBOSE=2

    - name: Archive PKGBUILD
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: PKGBUILD.${{github.sha}}
        retention-days: 7
        path: "build/arch/PKGBUILD"
