name: Hello world
on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- run: make -C scripts
    - run: apt-get source linux-image-unsigned-$(uname -r)
