name: Hello world
on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Build tools
      run: make -C tools
