name: Hello world
on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo build/deps
    - name: Build tools
      run: make -C tools
    - name: Build hlua
      run: make -C hlua
    - name: Build hpython
      run: make -C hpython
