name: Hello world
on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: hello
      run: pwd
    - name: what do we have here?
      run: ls ${{github.workspace}}
