name: Release
on:
  workflow_run:
    workflows: [ Build and test ]
    types: [ completed ]
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check version
        run: (tools/version -C && echo "RELEASE=1" || echo "RELEASE=") >> "$GITHUB_ENV"

      - name: Create artifacts directory
        if: ${{env.RELEASE == '1'}}
        run: |
          ARTIFACTS=$GITHUB_WORKSPACE/artifacts
          mkdir -p "$ARTIFACTS"
          echo "ARTIFACTS=$ARTIFACTS" >> "$GITHUB_ENV"

      - uses: actions/download-artifact@v3
        if: ${{env.RELEASE == '1'}}
        with:
          path: artifacts

      - name: Create release
        if: ${{env.RELEASE == '1'}}
        run: .github/release
        env:
          ARTIFACTS: artifacts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
